### ISSUE TITLE
where do I find the data file  (train_data.csv,   trade_data.csv )for those notebooks 

### ISSUE THREAD

**Issue by scotthuang1989** [AI4Finance-Foundation/FinRL-Tutorials#30]
where do I find the data file  (train_data.csv,   trade_data.csv )for those notebooks

**Comment by emarashliev** [comment]
I have the same issue

**Comment by oliverwang15** [comment]
Hi! You may generate those data by following the demo notebook [here](https://github.com/AI4Finance-Foundation/FinRL-Tutorials/blob/master/1-Introduction/Data_preparing.ipynb). The demo notebook is an example of getting data from Tushare, you may also try other data sources or even make your own data. Just to make share you have `tic`, `time`, and `close`  in your columns.

**Comment by emarashliev** [comment]
I don't want to be disrespectful, but this part 
`!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz 
!tar xvzf ta-lib-0.4.0-src.tar.gz
import os
os.chdir('ta-lib') 
!./configure --prefix=/usr
!make`
Looks very unclean and clumsy :/

**Comment by ZiyiXia** [comment]
> where do I find the data file (train_data.csv, trade_data.csv )for those notebooks
The files as well as the refined notebooks of Stock NeurIPS2018 were added in the directory `./1-Introduction/Stock_NeurIPS2018`
You can directly use the two provided csv files, or run the notebook _Stock_NeurIPS2018_1_Data.ipynb_ first and save the generated csv files.

**Comment by ZiyiXia** [comment]
> I don't want to be disrespectful, but this part
> 
> ```
> !wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz 
> !tar xvzf ta-lib-0.4.0-src.tar.gz
> import os
> os.chdir('ta-lib') 
> !./configure --prefix=/usr
> !make
> !make install
> ```
> 
> Looks very unclean and clumsy :/ Why we don't use conda here 🤔 like so `!conda install -y -c conda-forge ta-lib` ?

@emarashliev 
Thanks for your suggestion.
Indeed these are not neat enough, but we have to consider about the case that there are users running the notebooks on online editors like Google Colab. Using conda could only be more inconvenient in this situation. But if there's a better way with elegant codes that work for both users on Colab and local/conda environment, feel free to make adjustment and submit a PR!
