### ISSUE TITLE
Please solve this error:  Could not infer dtype of dict

### ISSUE THREAD

**Issue by Anupa-123** [AI4Finance-Foundation/FinRL-Tutorials#80]
RuntimeError                              Traceback (most recent call last)
[<ipython-input-89-50f7f586fcb0>](https://localhost:8080/#) in <cell line: 1>()
----> 1 account_value_erl=test(start_date = '2022-08-25',
      2                       end_date = '2022-08-31',
      3                       ticker_list = ticker_list,
      4                       data_source = 'alpaca',
      5                       time_interval= '1Min',

1 frames
[<ipython-input-66-c0ebf36876e4>](https://localhost:8080/#) in DRL_prediction(model_name, cwd, net_dimension, environment)
    102         with _torch.no_grad():
    103             for i in range(environment.max_step):
--> 104                 s_tensor = _torch.as_tensor((state,), device=device)
    105                 a_tensor = act(s_tensor)  # action_tanh = act.forward()
    106                 action = (

RuntimeError: Could not infer dtype of dict

**Comment by Anupa-123** [comment]
https://github.com/AI4Finance-Foundation/FinRL-Tutorials/blob/master/3-Practical/FinRL_PaperTrading_Demo.ipynb I am using this file and while testing line number 1151,  s_tensor = _torch.as_tensor((state,), device=device) this line creates an error.

**Comment by TheStoneMX** [comment]
~~~
        with _torch.no_grad():
            for i in range(environment.max_step):
                # state =     torch.as_tensor(ary_state, dtype=torch.float32, device=self.device)
                s_tensor = _torch.as_tensor((state,), dtype=torch.float32, device=device)
                a_tensor = act(s_tensor)  # action_tanh = act.forward()
                action = (
                    a_tensor.detach().cpu().numpy()[0]
                )  # not need detach(), because with torch.no_grad() outside
                state, reward, done, extra, _ = environment.step(action)

                total_asset = (
                    environment.amount
                    + (
                        environment.price_ary[environment.day] * environment.stocks
                    ).sum()
                )
                episode_total_assets.append(total_asset)
                episode_return = total_asset / environment.initial_total_asset
                episode_returns.append(episode_return)
                if done:
                    break
~~~

**Comment by TheStoneMX** [comment]
There are a couple of other things you need to fix on that loop....

I sometimes wonder why they have uploaded a broken d=code....

**Comment by Anupa-123** [comment]
Thanks a lot.
Can you help me in this also?

[/usr/local/lib/python3.10/site-packages/exchange_calendars/calendar_helpers.py](https://localhost:8080/#) in parse_date(date, param_name, calendar, raise_oob)
    377     if ts.tz is not None:
    378         raise ValueError(
--> 379             f"Parameter `{param_name}` received with timezone defined as '{str(ts.tz)}'"
    380             #f"Parameter `{param_name}` received with timezone defined as '{ts.tz.key}'"
    381             f" although a Date must be timezone naive."

AttributeError: 'UTC' object has no attribute 'key
